import { Product } from '../types/product.type';

export const products: Omit<Product, 'id'>[] = [
  {
    name: 'Wireless Headphones',
    description: 'Noise-cancelling Bluetooth headphones.',
    price: 199,
    image: '/images/headphones.png',
    stripePriceId: 'price_123456',
    isFeatured: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    name: 'Gaming Mouse',
    description: 'High-precision optical gaming mouse.',
    price: 79,
    image: '/images/mouse.png',
    stripePriceId: 'price_789012',
    isFeatured: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // --- New 10 products ---
  {
    name: 'Mechanical Keyboard',
    description: 'RGB backlit keyboard with tactile switches.',
    price: 149,
    image: '/images/keyboard.png',
    stripePriceId: 'price_300001',
    isFeatured: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    name: '4K Monitor',
    description: 'Ultra HD display with vivid color accuracy.',
    price: 399,
    image: '/images/monitor.png',
    stripePriceId: 'price_300002',
    isFeatured: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    name: 'Portable SSD',
    description: '1TB high-speed external solid state drive.',
    price: 129,
    image: '/images/ssd.png',
    stripePriceId: 'price_300003',
    isFeatured: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    name: 'Smartwatch',
    description: 'Fitness tracking smartwatch with GPS.',
    price: 249,
    image: '/images/smartwatch.png',
    stripePriceId: 'price_300004',
    isFeatured: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    name: 'Webcam Pro',
    description: '1080p HD webcam with autofocus and stereo mic.',
    price: 99,
    image: '/images/webcam.png',
    stripePriceId: 'price_300005',
    isFeatured: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    name: 'Ergonomic Chair',
    description: 'Adjustable office chair designed for long sessions.',
    price: 299,
    image: '/images/chair.png',
    stripePriceId: 'price_300006',
    isFeatured: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    name: 'USB-C Hub',
    description: '8-in-1 USB-C hub with HDMI, USB-A, and SD card slots.',
    price: 59,
    image: '/images/hub.png',
    stripePriceId: 'price_300007',
    isFeatured: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    name: 'Bluetooth Speaker',
    description: 'Portable speaker with deep bass and 12-hour battery.',
    price: 89,
    image: '/images/speaker.png',
    stripePriceId: 'price_300008',
    isFeatured: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    name: 'Desk Lamp LED',
    description: 'Adjustable LED lamp with brightness presets.',
    price: 49,
    image: '/images/lamp.png',
    stripePriceId: 'price_300009',
    isFeatured: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];
